### ISSUE TITLE
How to change font for heading.

### ISSUE THREAD

**Issue by eugeneelchugin** [enactjs/moonstone#30]
Hi! I'm trying to change font for heading. For `@enact/moonstone/Button` I simply set css prop like that:
```javascript
import MoonButton from '@enact/moonstone/Button'
import buttonCss from 'MyButtonCss.module.scss'

const Button = (props) => <MoonButton {...props} css={buttonCss} />
``` 
and this works, because of you fill publicClassNames prop in ButtonBase. But for heading you don't did it.
```javascript
styles: {
	css: componentCss,
	className: 'heading'
}
```
Maybe can you add public class names for heading or tell me another way how to do it? Or maybe there is the way how to change font globally for whole moonstone.

**Comment by Djspaceg** [comment]
Good news! You don't even need to use our internal-classname-override system to set these styles. You can simply add your own class name to the component, and then apply styles to that class names in your SASS (or LESS or CSS) files like normal. Both `Button` and `Heading` follow the standard rules, so this should just all work out of the box.

Your customized class name doesn't need to match anything we'd assigned to the component either (unlike the override system).

```javascript
const Button = (props) => <MoonButton {...props} className={buttonCss.myCoolButton} />
const Heading = (props) => <MoonHeading {...props} className={buttonCss.myCoolHeading} />
```

And if you're using `kind()`  to create these, it automatically handles the class name merging, and offers the convenience of `append` and `join` methods that leverage features of the public `classnames` module linked from NPM.

**Comment by eugeneelchugin** [comment]
Unfortunatelly, it doesn't work, because moonstone styles has complex css selectors for heading.
**My Heading.module.scss**
```sass
@import "../variables";

.myCoolHeading {
    font-family: $ru-font;

    &.small {
        font-family: $ru-font;
    }
}
```
**My Heading.tsx**
```typescript
import React from 'react';
import kind from '@enact/core/kind';
import MoonHeading, { HeadingProps } from '@enact/moonstone/Heading';
import headingCss from './Heading.module.scss';

const Heading: React.ComponentType<HeadingProps & React.HTMLProps<HTMLElement>> = kind({
    name: 'Heading',
    styles: {
        css: headingCss,
        className: headingCss.myCoolHeading,
    },
    render: (props: any) => (
        <MoonHeading {...props} />
    )
});

export default Heading;
```
**And usage**
```javascript
<Heading showLine spacing="small">
    This is on English, а это по-русски!
</Heading>
```

After rendering we'll see that h4 will have many css rules particularly:
```css
.myCoolHeading {
    font-family: Consolas;
}

.heading.medium {
    font-family: "Moonstone";
}

.heading.smallSpacing {
   /* no rule for font */
}

/* and no custom rule .myCoolHeading.small because of disabled publicClassNames */
```
And browser folows specifity rule to select .heading.medium rule. I tried set !important to .myCoolHeading, and it works, but this is so ugly.

**Comment by Djspaceg** [comment]
Oops, you're absolutely right.

Adding another level of precedence to your custom class could solve the problem without requiring an `!important`. You could hook onto the locale for Russian if you'd like: `.enact-locale-ru`. This class is applied when the current locale is set to Russian (and an equivalent `.enact-locale-*`) for all 2-letter language codes, or 2-letter region codes (`US`/`GB`/`RU`), or the full locale code (`en-US`/`ru-RU`). You'll access these by wrapping them in a `:global()` wrapper, so they don't get obfuscated. The result would be like this, which _should_ (I think) override the pair of selectors:
```css
:global(.enact-locale-ru) .myCoolHeading {
    font-family: Consolas;
}
```

Alternatively, you could simply add a second class of your own (I know, this is pretty lame, but Moonstone wasn't really designed to be customized, and was intended as more fixed and opinionated).
```css
.myCoolHeading.customFonts {
    font-family: Consolas;
}
```

```javascript
const Heading = (props) => <MoonHeading {...props} className={buttonCss.myCoolHeading + ' ' buttonCSS.customFonts} />
// or
import classnames from 'classnames';

const Heading = (props) => <MoonHeading {...props} className={classnames(buttonCss.myCoolHeading, buttonCSS.customFonts)} />
```

And alternatively alternatively, you can hook onto the Moonstone font definitions and set your own to "layer on" an additional set of glyphs if your font family happens to match the style of the Moonstone fonts.
```css
@font-face {
  font-family: "Moonstone";
  src: local("Consolas");
  font-weight: normal;
}
```
You'd need more than this, since this will only target the "normal" font-weight. Moonstone has weights of: 300, 500, 600, and 700 _(with several more that aren't really used)_, as well as the italic version of each of these. You can see the generated code by searching the compiled stylesheets for `/* ----- Moonstone ------ */` which will be immediately followed by an `@font-face` rule like above.

_This would be a larger, more global, solution to this issue._

In the meantime, I'll discuss with the team to determine if we _can_ open up some additional classes on the `Heading` for customization, which would allow your code above to work as-is.
> ```css
> @import "../variables";
> 
> .myCoolHeading {
>     font-family: $ru-font;
> 
>     &.small {
>         font-family: $ru-font;
>     }
> }
> ```

**Comment by eugeneelchugin** [comment]
Yeah, @font-face workaround is realy what I looking for. Thank you so much!
I imported my `ru.scss` in root `index.tsx`.
**ru.scss**
```scss
$ru-font: Consolas;
$weights: normal, 300, 500, 600, 700;

@each $weight in $weights {
    @font-face {
        font-family: "Moonstone";
        src:local($ru-font);
        font-weight: $weight;
    }
}
```
But I will follow this topic for news about public class names for Heading :) But maybe your designers can add some cyrillic letters to font? Some letters has same way of rightings:

| Ru uppercase | En analog | Ru lowercase | En analog |
| --- | --- | --- | --- |
| А | A | а | а |
| Б | Like B without upper rounding | б |  |
| В | B | в | Downscaled B |
| Г | Like Б without roundngs | г | Downscaled Г |
| Д |  | д | Downscaled Д |
| Е | E | е | e |
| Ё | E with ¨ | ё | ё |
| Ж |  | ж |  |
| З | Double c but vertically | з | Downscaled |
| И | N | и | Downscaled or u |
| Й | N with ˘ | й | Downscaled or u with ˘ |
| К | K | к | like k |
| Л |  | л | Downscaled |
| М | M | м | Downscaled |
| Н | H | н | Downscaled |
| О | O | о | o |
| П | Union of Г and mirrored Г | п | Downscaled |
| Р | P | р | p |
| С | C | с | c |
| Т | T | т | Downscaled |
| У | Upscaled y | у | y |
| Ф |  | ф |  |
| Х | X | х | x |
| Ц | Mirrored П | ц | Downscaled |
| Ч | Like h but rotated by 180 degrees | ч | Downscaled |
| Ш | Doubled mirrored П | ш | Downscaled |
| Щ | Like Ш | щ | Downscaled |
| Ъ | b | Ъ | Downscaled |
| Ы | bI | ы | Downscaled |
| Ь | b | ь | Downscaled |
| Э | Like € | э | Downscaled |
| Ю | I-O | ю | Downscaled |
| Я | R | я | Downscaled |

**Comment by Djspaceg** [comment]
I think you may be in luck! The latest 2020 TVs include a new font called "LG Smart UI", which unifies almost all languages into a single family of fonts, which includes Cyrillic glyphs and many more. It's the common font for all products moving forward. :) The above table renders correctly in this new font family.

Of course, this is only relevant to you if you're developing TV apps, since the fonts are not available for redistribution.
