### ISSUE TITLE
Scrollers are broken on my LG TV

### ISSUE THREAD

**Issue by MarcelRichter-GitHub** [enactjs/moonstone#37]
Hello,
I am having issues with getting scrollers working on my LG 32LK6200PLA test device.
They work correctly when running the app in Firefox on PC, but when I run it on the TV the scroller doesn't function properly.
The screen doesn't move with the selection and only when the very last item is reached, it will scroll down.

Videos showcasing the issue:

Broken functionality on TV:

https://user-images.githubusercontent.com/44291436/103035829-0b147880-4560-11eb-85e9-053aaca11a35.mp4

Expected functionality on PC:

https://user-images.githubusercontent.com/44291436/103035870-22536600-4560-11eb-89f1-cdba2a67d17b.mp4

Both TV as well as Enact are up to date.

I also attached the showcased app. It has been renamed from App.js to App.txt to get a GitHub allowed file type. 
[App.js](https://github.com/enactjs/moonstone/files/5737070/App.txt)

**Comment by jeonghee27** [comment]
Hello.  @Marcel1202 

The attached app code and video were helpful to check the issue. Thank you.

It is a problem caused by the size of the Scroller when the Scroller cannot define its own height.
You could simply reproduce the issue on PC using outer div.
```
			<div>
				<Scroller>
					<Item>Hello I'm an item</Item>
```

And you can debug the wrong height of Scroller on browser Inspector.
"enact_ui_Scrollable_Scrollable_scrollable moonstone" 

When the Scroller cannot define its own height, you need to specify some height values.

```
import ri from '@enact/ui/resolution';
...
			<div>
				<Scroller style={{height: ri.scaleToRem(1080)}}>
					<Item>Hello I'm an item</Item>
```

I hope this comment is helpful and works. 

Thank you.

**Comment by MarcelRichter-GitHub** [comment]
Hello @jeonghee27.
Thank you for your quick response.
As you said adding div tags made the problem, at least kind of, reproducable on PC (although the overscroll behaviour was still different).
And adding a height to the Scroller component did fix the problem on PC but unfortunately not on the TV.
I confirmed that height and width are set correctly both by checking using the inspector on PC, as well as setting it to only half the screen size on TV.

I tried:
- Setting width and height directly in the render method and inside a less file
- Disabling resolution independence
- Copying and pasting this [example](https://enactjs.com/docs/developer-guide/moonstone/virtual-list-scroller/#scroller), replacing the scroller content with a bunch of items.
- Specifying the height of the items

I also checked when onScrollStart and onScrollStop are called, and confirmed that they are called whenever the Scroller actually is scrolling.

**Comment by jeonghee27** [comment]
Hello.
> I confirmed that height and width are set correctly both 

Does that mean the scroller height doesn't become overflow the screen?

I've tried to reproduced as you did. But I cannot reproduced the problem. 
Currently It is difficult to determine the exact cause.

If the content has list of items, how about using VirtualList instead of Scroller?

Or, 
It may be related to a chromium engine related to Scroll and focus behavior.
The latest Moonstone does not guarantee compatibility with the previous version of WebOS because of much changes in Chromium. So I recommend to use the previous version of Moonstone 2.5.2 or lower.
(https://www.npmjs.com/package/@enact/moonstone)

**Comment by MarcelRichter-GitHub** [comment]
Hello,
thank you for your help.
Downgrading moonstone to version 2.5.3 did the trick.
The device runs webOS 4.1, which seems to be out of date since 2019.
I think the LG store allows me to upload different IPKs for different versions of webOS, so I'll create one bundled with Moonstone 3 and a legacy one with Monstone 2.

**Comment by jeonghee27** [comment]
I'm glad the old version works.
Chromium versions of WebOS 4 and 5 are different. so it may be cumbersome, but I think you need to do so.
